gradle/eclipse-project-layout.gradle
gradle/java-compiler-settings.gradle

Consistent use of tabs instead of spaces
Use single whitespace between brackets

[format] Streamlined whitespaces

---

.gitignore
.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.core.idea.tests/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.idea.common.types.tests/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.idea.example.entities.ide/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.idea.example.entities.idea/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.idea.example.entities/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.idea.junit/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.idea.sdomain.ide/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.idea.sdomain.idea.tests/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.idea.sdomain.idea/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.idea.sdomain/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.idea/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.purexbase.idea/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.testlanguages.idea/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.xbase.idea.tests/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.xtext.idea.tests/.settings/org.eclipse.buildship.core.prefs
org.eclipse.xtext.xtext.idea/.settings/org.eclipse.buildship.core.prefs

connection.project.dir changed to composite build location in new
umbrella project
value 'containers' added by Buildship

Gradle composite

---

org.eclipse.xtext.idea.sdomain.idea.tests/xtend-gen/org/eclipse/xtext/idea/sdomain/idea/tests/psi/XtextPsiReferenceTestContext.java
org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/common/types/PsiBasedTypeFactory.java

[501975] Null guard for switch statements

---

org.eclipse.xtext.idea.junit/xtend-gen/org/eclipse/xtext/idea/tests/LightToolingTest.java
org.eclipse.xtext.idea.junit/xtend-gen/org/eclipse/xtext/idea/tests/TestDecoratorProcessor.java
org.eclipse.xtext.idea.junit/xtend-gen/org/eclipse/xtext/idea/tests/debug/AbstractDebuggerTestCase.java
org.eclipse.xtext.idea.junit/xtend-gen/org/eclipse/xtext/idea/tests/parsing/NodeModelPrinter.java
org.eclipse.xtext.idea.junit/xtend-gen/org/eclipse/xtext/idea/tests/parsing/XtextResourceAsserts.java
org.eclipse.xtext.idea.sdomain.idea.tests/xtend-gen/org/eclipse/xtext/idea/sdomain/idea/tests/containers/ResolveScopeBasedContainerManagerTest.java
org.eclipse.xtext.idea.sdomain/xtend-gen/org/eclipse/xtext/idea/sdomain/generator/SDomainGenerator.java
org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/documentation/IdeaDeclarationDocumentationProvider.java
org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/extensions/AbstractExecutableExtensionPoint.java
org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/filesystem/IdeaWorkspaceConfig.java
org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/lang/GrammarAwareErrorElementType.java
org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/lang/GrammarAwarePsiErrorElement.java
org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/parser/AbstractPsiAntlrParser.java
org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/psi/impl/PsiEObjectFactoryImpl.java
org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/psi/impl/PsiEObjectIdentifierImpl.java
org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/psi/impl/PsiEObjectImpl.java
org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/psi/impl/PsiNamedEObjectImpl.java
org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/psi/stubs/XtextFileElementType.java
org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/xbase/idea/presentation/XbaseItemPresentationProvider.java
org.eclipse.xtext.xtext.idea.tests/xtend-gen/org/eclipse/xtext/xtext/idea/tests/wizard/IdeaProjectCreatorTest.java
org.eclipse.xtext.xtext.idea/xtend-gen/org/eclipse/xtext/idea/wizard/XtextModuleBuilder.java

Changes to generated Xtend code due to compiler optimization

[507077] Do not emit empty concatenation

---

org.eclipse.xtext.core.idea.tests/tests/org/eclipse/xtext/parser/terminalrules/IdeaUnicodeTest.xtend
org.eclipse.xtext.idea.junit/src/org/eclipse/xtext/idea/tests/parsing/AbstractLanguageParsingTestCase.xtend

fixed broken test #41

---

org.eclipse.xtext.idea.common.types.tests/plugin.xml

fixed errors in eclipse

---

gradle/bootstrap-setup.gradle
gradle/versions.gradle

update to 2.14

---

org.eclipse.xtext.core.idea.tests/.classpath
org.eclipse.xtext.idea.common.types.tests/.classpath
org.eclipse.xtext.idea.example.entities.idea/.classpath
org.eclipse.xtext.idea.example.entities/.classpath
org.eclipse.xtext.idea.junit/.classpath
org.eclipse.xtext.idea.sdomain.ide/.classpath
org.eclipse.xtext.idea.sdomain.idea.tests/.classpath
org.eclipse.xtext.idea.sdomain.idea/.classpath
org.eclipse.xtext.idea.sdomain/.classpath
org.eclipse.xtext.idea/.classpath
org.eclipse.xtext.purexbase.idea/.classpath
org.eclipse.xtext.testlanguages.idea/.classpath
org.eclipse.xtext.xbase.idea.tests/.classpath
org.eclipse.xtext.xtext.idea.tests/.classpath
org.eclipse.xtext.xtext.idea/.classpath

[eclipse/xtext#1129] Automatic changes by Buildship

---

org.eclipse.xtext.core.idea.tests/.classpath
org.eclipse.xtext.idea.common.types.tests/.classpath
org.eclipse.xtext.idea.example.entities.idea/.classpath
org.eclipse.xtext.idea.example.entities/.classpath
org.eclipse.xtext.idea.junit/.classpath
org.eclipse.xtext.idea.sdomain.ide/.classpath
org.eclipse.xtext.idea.sdomain.idea.tests/.classpath
org.eclipse.xtext.idea.sdomain.idea/.classpath
org.eclipse.xtext.idea.sdomain/.classpath
org.eclipse.xtext.idea/.classpath
org.eclipse.xtext.purexbase.idea/.classpath
org.eclipse.xtext.testlanguages.idea/.classpath
org.eclipse.xtext.xbase.idea.tests/.classpath
org.eclipse.xtext.xtext.idea.tests/.classpath
org.eclipse.xtext.xtext.idea/.classpath

- added including pattern for classpathentry src

[gradle] Classpath changes by Buildship

---

org.eclipse.xtext.idea/src/org/eclipse/xtext/xbase/idea/facet/XbaseGeneratorConfigProvider.xtend

more j9 compatibility

---

org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/JavaIoFileSystemTest.java

regenerated

---

org.eclipse.xtext.xtext.idea/src-gen/org/eclipse/xtext/idea/parser/antlr/internal/PsiInternalXtext.g
org.eclipse.xtext.xtext.idea/src-gen/org/eclipse/xtext/idea/parser/antlr/internal/PsiInternalXtextParser.java

[eclipse/xtext-core#664] allow multiple annotations

[eclipse/xtext-core#664] allow multiple annotations

---

org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/completion/XtendCompletionContributor.xtend
org.eclipse.xtext.idea.junit/src/org/eclipse/xtext/idea/tests/LightToolingTest.xtend

fixed redundant modifiers

---

org.eclipse.xtext.xtext.idea/src/org/eclipse/xtext/idea/wizard/XtextWizardStep.xtend

fixed idea compile error in wizard

---

gradle/bootstrap-setup.gradle
gradle/versions.gradle

[eclipse/xtext#1178] bootstrap against 2.14

[eclipse/xtext#1178] bootstrap against 2.14

---

org.eclipse.xtext.xtext.idea/src/org/eclipse/xtext/idea/wizard/IdeaProjectCreator.xtend

Introduced by https://github.com/eclipse/xtext-core/pull/775
Signed-off-by: Arne Deutsch <Arne.Deutsch@itemis.de>

Fix compile error.

---

org.eclipse.xtext.idea.common.types.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.idea.example.entities.ide/META-INF/MANIFEST.MF
org.eclipse.xtext.idea.example.entities/META-INF/MANIFEST.MF
org.eclipse.xtext.idea.sdomain/META-INF/MANIFEST.MF

[#1238] Restrict org.antlr.runtime version to 3.2.0

---

org.eclipse.xtext.idea.common.types.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.idea.example.entities/META-INF/MANIFEST.MF

[eclipse/xtext#1266] Update to ASM 6.2

[eclipse/xtext#1266] Update to ASM 6.2

---

gradle/versions.gradle
org.eclipse.xtend.idea/META-INF/plugin.xml

updated versions to 2.16.0

---

gradle/bootstrap-setup.gradle

build against 2.15

---

gradle/bootstrap-setup.gradle
gradle/versions.gradle

adapt to pattern in other modules

---

org.eclipse.xtext.idea.common.types.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.idea.example.entities/META-INF/MANIFEST.MF

[eclipse/xtext#1325] switch to ASM 7

[eclipse/xtext#1325] switch to ASM 7

---

gradle/versions.gradle
org.eclipse.xtend.idea/META-INF/plugin.xml

change version 2.16.0 -> 2.17.0

---

gradle.properties
gradle/versions.gradle

[eclipse/xtext#1394] bootstrap against 2.17.0.M2

[eclipse/xtext#1394] bootstrap against 2.17.0.M2

---

org.eclipse.xtend.idea.tests/Xtend Test Intellij.launch
org.eclipse.xtext.core.idea.tests/.classpath
org.eclipse.xtext.idea.common.types.tests/.classpath
org.eclipse.xtext.idea.example.entities.ide/.classpath
org.eclipse.xtext.idea.example.entities.idea/.classpath
org.eclipse.xtext.idea.example.entities/.classpath
org.eclipse.xtext.idea.junit/.classpath
org.eclipse.xtext.idea.sdomain.ide/.classpath
org.eclipse.xtext.idea.sdomain.idea.tests/.classpath
org.eclipse.xtext.idea.sdomain.idea/.classpath
org.eclipse.xtext.idea.sdomain/.classpath
org.eclipse.xtext.idea/.classpath
org.eclipse.xtext.purexbase.idea/.classpath
org.eclipse.xtext.testlanguages.idea/.classpath
org.eclipse.xtext.xbase.idea.tests/.classpath
org.eclipse.xtext.xtext.idea.tests/.classpath
org.eclipse.xtext.xtext.idea/.classpath

[eclipse/xtext#1274] Updated .classpath by Gradle

---

gradle/versions.gradle
org.eclipse.xtend.idea/META-INF/plugin.xml

[eclipse/xtext#1414] prepared master for version 2.18.0 

[eclipse/xtext#1414] prepared master for version 2.18.0
